import type {
  BindingOption,
  CalendarStyleOption,
  CoverSystem,
  CoverType,
  LayoutMode,
  PackOption,
  SeparatorOption,
  SizeOption,
  StickerOption,
  SwatchOption,
  TemplatePreset,
  Tone,
  VisionStyleOption,
} from "./types";

export const PLANNER_YEAR = 2027;

export const SIZES: SizeOption[] = [
  {
    id: "a5",
    label: { es: "A5 estandar (14.8 x 21 cm)", en: "Standard A5 (5.8 x 8.3 in)" },
    dims: "14.8 x 21 cm",
    ratio: 14.8 / 21,
    standard: true,
    priceUsd: 0,
  },
  {
    id: "personal",
    label: { es: "Personal compacta (9.5 x 17 cm)", en: "Personal compact (3.7 x 6.7 in)" },
    dims: "9.5 x 17 cm",
    ratio: 9.5 / 17,
    standard: false,
    priceUsd: -5,
  },
  {
    id: "b6",
    label: { es: "B6 de bolsillo (12.6 x 17.6 cm)", en: "B6 pocket (5.0 x 6.9 in)" },
    dims: "12.6 x 17.6 cm",
    ratio: 12.6 / 17.6,
    standard: false,
    priceUsd: -3,
  },
  {
    id: "media-carta",
    label: { es: "Media carta (17 x 22 cm)", en: "Half letter (6.7 x 8.7 in)" },
    dims: "17 x 22 cm",
    ratio: 17 / 22,
    standard: false,
    priceUsd: 4,
  },
  {
    id: "a4",
    label: { es: "A4 ejecutiva de escritorio (21 x 29.7 cm)", en: "A4 executive desk (8.3 x 11.7 in)" },
    dims: "21 x 29.7 cm",
    ratio: 21 / 29.7,
    standard: false,
    priceUsd: 9,
  },
  {
    id: "cuadrado",
    label: { es: "Cuadrada de escritorio (19 x 19 cm)", en: "Square desktop (7.5 x 7.5 in)" },
    dims: "19 x 19 cm",
    ratio: 1,
    standard: false,
    priceUsd: 6,
  },
];

export const COVER_TYPES: CoverType[] = [
  { id: "tapa-dura", label: { es: "Tapa dura lisa", en: "Plain hardcover" }, swatch: "#e7ded0", illustrated: false, priceUsd: 0 },
  { id: "cuero-vegano", label: { es: "Cuero vegano", en: "Vegan leather" }, swatch: "#5a4235", illustrated: false, priceUsd: 6 },
  { id: "cuero-premium", label: { es: "Cuero premium", en: "Premium leather" }, swatch: "#24211d", illustrated: false, priceUsd: 14 },
  { id: "lino", label: { es: "Lino texturizado", en: "Textured linen" }, swatch: "#d8c7ae", illustrated: false, priceUsd: 3 },
  { id: "ilustrada-floral", label: { es: "Tapa ilustrada floral", en: "Floral illustrated cover" }, swatch: "#c98fa3", illustrated: true, priceUsd: 5 },
  { id: "ilustrada-abstracta", label: { es: "Tapa ilustrada abstracta", en: "Abstract illustrated cover" }, swatch: "#5f74c8", illustrated: true, priceUsd: 5 },
  { id: "ilustrada-mistica", label: { es: "Tapa mistica (sol y luna)", en: "Mystic cover (sun & moon)" }, swatch: "#d9707a", illustrated: true, priceUsd: 7 },
  { id: "ilustrada-retro", label: { es: "Tapa retro divertida", en: "Fun retro cover" }, swatch: "#8fd6c9", illustrated: true, priceUsd: 6 },
  { id: "minimalista", label: { es: "Tapa minimalista", en: "Minimalist cover" }, swatch: "#f7f2ea", illustrated: false, priceUsd: 0 },
];

export const COVER_FITS = {
  full: { es: "Tapa cubre completa la hoja", en: "Cover fully wraps the pages" },
  exact: { es: "Tapa del tamano exacto de la hoja", en: "Cover matches exact page size" },
};

export const BINDINGS: BindingOption[] = [
  { id: "anillado-dorado", label: { es: "Anillado dorado", en: "Gold ring binding" }, priceUsd: 0 },
  { id: "anillado-negro", label: { es: "Anillado negro", en: "Black ring binding" }, priceUsd: 0 },
  { id: "discos", label: { es: "Discos removibles", en: "Removable discs" }, priceUsd: 5 },
  { id: "cosido", label: { es: "Empastado cosido", en: "Sewn binding" }, priceUsd: 10 },
  { id: "cuero-flexible", label: { es: "Cuero flexible", en: "Flexible leather binding" }, priceUsd: 15 },
];

export const SEPARATORS: SeparatorOption[] = [
  { id: "cartulina", label: { es: "Cartulina de color solido", en: "Solid color cardstock" } },
  { id: "pestanas", label: { es: "Pestanas troqueladas", en: "Die-cut tabs" } },
  { id: "kraft", label: { es: "Kraft numerado", en: "Numbered kraft paper" } },
  { id: "laminado", label: { es: "Laminado ilustrado", en: "Illustrated laminate" } },
];

export const RING_COLORS: SwatchOption[] = [
  { id: "dorado", label: { es: "Dorado", en: "Gold" }, hex: "#c9a24b" },
  { id: "plateado", label: { es: "Plateado", en: "Silver" }, hex: "#b8bcc4" },
  { id: "negro", label: { es: "Negro", en: "Black" }, hex: "#24211d" },
  { id: "rose-gold", label: { es: "Rose gold", en: "Rose gold" }, hex: "#c98f80" },
  { id: "cobre", label: { es: "Cobre", en: "Copper" }, hex: "#a15c37" },
];

export const ELASTIC_COLORS: SwatchOption[] = [
  { id: "elastico-negro", label: { es: "Negro", en: "Black" }, hex: "#24211d" },
  { id: "elastico-dorado", label: { es: "Dorado", en: "Gold" }, hex: "#c9a24b" },
  { id: "elastico-rosa", label: { es: "Rosa polvo", en: "Dusty rose" }, hex: "#c98fa3" },
  { id: "elastico-crema", label: { es: "Crema", en: "Cream" }, hex: "#f3e9d8" },
  { id: "elastico-verde", label: { es: "Verde salvia", en: "Sage green" }, hex: "#7f9070" },
];

export const COVER_SYSTEMS: CoverSystem[] = [
  {
    id: "minimalista",
    label: { es: "Minimalista", en: "Minimalist" },
    description: {
      es: "Sans geometrica y una linea fina. Nada de mas.",
      en: "Geometric sans and a thin rule. Nothing extra.",
    },
    titleFont: "var(--font-minimal), 'Helvetica Neue', sans-serif",
    phraseFont: "var(--font-serif), Georgia, serif",
    innerFont: "var(--font-minimal), 'Helvetica Neue', sans-serif",
    align: "center",
    titleCase: "upper",
    weight: 500,
    motif: "line",
  },
  {
    id: "ejecutiva",
    label: { es: "Ejecutiva", en: "Executive" },
    description: {
      es: "Serif editorial serio, alineado a la izquierda, con estructura.",
      en: "Serious editorial serif, left-aligned, structured.",
    },
    titleFont: "var(--font-serif), Georgia, serif",
    phraseFont: "var(--font-geist-sans), sans-serif",
    innerFont: "var(--font-geist-sans), sans-serif",
    align: "left",
    titleCase: "normal",
    weight: 600,
    motif: "tab",
  },
  {
    id: "romantica",
    label: { es: "Romantica / poetica", en: "Romantic / poetic" },
    description: {
      es: "Serif italica delicada, centrada, con espacio para respirar.",
      en: "Delicate italic serif, centered, room to breathe.",
    },
    titleFont: "var(--font-romantic), Georgia, serif",
    phraseFont: "var(--font-romantic), Georgia, serif",
    innerFont: "var(--font-romantic), Georgia, serif",
    align: "center",
    titleCase: "normal",
    weight: 500,
    motif: "flourish",
  },
  {
    id: "creativa",
    label: { es: "Creativa / artistica", en: "Creative / artistic" },
    description: {
      es: "Serif expresiva con caracter, composicion libre.",
      en: "Expressive serif with character, free composition.",
    },
    titleFont: "var(--font-creative), Georgia, serif",
    phraseFont: "var(--font-creative), Georgia, serif",
    innerFont: "var(--font-geist-sans), sans-serif",
    align: "left",
    titleCase: "normal",
    weight: 500,
    motif: "dot",
  },
  {
    id: "intensa",
    label: { es: "Intensa", en: "Intense" },
    description: {
      es: "Display condensado en mayusculas, contraste fuerte.",
      en: "Condensed display caps, strong contrast.",
    },
    titleFont: "var(--font-intense), sans-serif",
    phraseFont: "var(--font-geist-sans), sans-serif",
    innerFont: "var(--font-geist-sans), sans-serif",
    align: "center",
    titleCase: "upper",
    weight: 400,
    motif: "frame",
  },
  {
    id: "editorial",
    label: { es: "Sofisticada / editorial", en: "Sophisticated / editorial" },
    description: {
      es: "Serif italica de revista, con kicker en mayusculas pequenas.",
      en: "Magazine-style italic serif, small-caps kicker.",
    },
    titleFont: "var(--font-serif), Georgia, serif",
    phraseFont: "var(--font-serif), Georgia, serif",
    innerFont: "var(--font-serif), Georgia, serif",
    align: "center",
    titleCase: "normal",
    weight: 600,
    motif: "line",
  },
];

export const STICKERS: StickerOption[] = [
  { id: "productivo", label: { es: "Productivo", en: "Productive" }, color: "#2f8f6f", icon: "✓" },
  { id: "creativo", label: { es: "Creativo", en: "Creative" }, color: "#db7b36", icon: "✨" },
  { id: "descanso", label: { es: "Descanso", en: "Rest" }, color: "#5f74c8", icon: "☾" },
  { id: "finanzas", label: { es: "Finanzas", en: "Finance" }, color: "#2f8f6f", icon: "$" },
  { id: "aprendizaje", label: { es: "Aprendizaje", en: "Learning" }, color: "#8b6fc7", icon: "☁" },
  { id: "salud", label: { es: "Salud", en: "Health" }, color: "#c74b62", icon: "♥" },
  { id: "importante", label: { es: "Importante", en: "Important" }, color: "#c74b62", icon: "!" },
  { id: "dia-dificil", label: { es: "Dia dificil", en: "Hard day" }, color: "#766d63", icon: "☁" },
  { id: "dia-excelente", label: { es: "Dia excelente", en: "Great day" }, color: "#db7b36", icon: "★" },
  { id: "recordatorio", label: { es: "Recordatorio", en: "Reminder" }, color: "#5f74c8", icon: "●" },
  { id: "mini-meta", label: { es: "Mini meta", en: "Mini goal" }, color: "#2f8f6f", icon: "▲" },
  { id: "ciclo", label: { es: "Ciclo (discreto)", en: "Cycle (discreet)" }, color: "#c98fa3", icon: "○", subtle: true },
];

export const VISION_STYLES: VisionStyleOption[] = [
  { id: "floral", label: { es: "Floral", en: "Floral" } },
  { id: "abstracto", label: { es: "Abstracto", en: "Abstract" } },
  { id: "minimal-collage", label: { es: "Minimal collage", en: "Minimal collage" } },
  { id: "moodboard", label: { es: "Moodboard fotografico", en: "Photo moodboard" } },
];

export const CALENDAR_STYLES: CalendarStyleOption[] = [
  { id: "clasico", label: { es: "Clasico de lineas", en: "Classic lined" } },
  { id: "bloques", label: { es: "Bloques de color", en: "Color blocks" } },
  { id: "minimal-numeros", label: { es: "Minimal por numeros", en: "Minimal numbers" } },
  { id: "ilustrado", label: { es: "Ilustrado floral", en: "Floral illustrated" } },
];

export const QUOTES: Record<Tone, { es: string; en: string }> = {
  serena: {
    es: "El dia se vuelve liviano cuando cada hora tiene una intencion honesta.",
    en: "The day feels lighter when every hour carries an honest intention.",
  },
  intensa: {
    es: "No esperes claridad total: empieza, ajusta y deja que la accion piense contigo.",
    en: "Don't wait for full clarity: start, adjust, and let action think with you.",
  },
  poetica: {
    es: "Hay una forma de futuro escondida en lo que cuidas hoy.",
    en: "There is a shape of the future hidden in what you care for today.",
  },
  filosofica: {
    es: "Ordenar el tiempo tambien es preguntarte que vida merece tu atencion.",
    en: "Ordering your time is also asking which life deserves your attention.",
  },
};

export const LAYOUTS: Array<{ key: LayoutMode; label: { es: string; en: string }; detail: { es: string; en: string } }> = [
  {
    key: "horaria",
    label: { es: "Una hoja por dia, por horas", en: "One page per day, by hours" },
    detail: { es: "Horas completas, recordatorio, frase y mini metas.", en: "Full hours, reminder, quote and mini goals." },
  },
  {
    key: "areas",
    label: { es: "Por areas de conocimiento", en: "By knowledge areas" },
    detail: {
      es: "Trabajo, aprendizaje, desarrollo personal e independencia financiera primero.",
      en: "Work, learning, personal growth and financial independence first.",
    },
  },
  {
    key: "libre",
    label: { es: "Pagina libre con frase y mini metas", en: "Free page with quote and mini goals" },
    detail: { es: "Menos estructura, mas espacio para escribir y reflexionar.", en: "Less structure, more room to write and reflect." },
  },
  {
    key: "dual",
    label: { es: "Dia + revision nocturna", en: "Day + nightly review" },
    detail: { es: "Plan del dia a la izquierda y cierre consciente a la derecha.", en: "Day plan on the left, mindful close on the right." },
  },
];

export const PACKS: PackOption[] = [
  {
    id: "solo-agenda",
    name: { es: "Solo Agenda", en: "Planner Only" },
    priceUsd: 28,
    includes: { agenda: true, calendar: false, visionBoard: false, stickers: false, tools: false },
    components: { es: "Agenda A5 con portada, distribucion diaria y frase.", en: "A5 planner with cover, daily layout and quote." },
  },
  {
    id: "agenda-calendario",
    name: { es: "Agenda + Calendario", en: "Planner + Calendar" },
    priceUsd: 39,
    includes: { agenda: true, calendar: true, visionBoard: false, stickers: false, tools: false },
    components: { es: "Agenda A5 y calendario de escritorio mensual.", en: "A5 planner and a monthly desktop calendar." },
  },
  {
    id: "agenda-calendario-vision",
    name: { es: "Agenda + Calendario + Vision Board", en: "Planner + Calendar + Vision Board" },
    priceUsd: 52,
    includes: { agenda: true, calendar: true, visionBoard: true, stickers: false, tools: false },
    components: { es: "Agenda A5, calendario mensual y vision board para metas visuales.", en: "A5 planner, monthly calendar and a vision board for visual goals." },
  },
  {
    id: "premium",
    name: { es: "Pack Premium", en: "Premium Pack" },
    priceUsd: 69,
    includes: { agenda: true, calendar: true, visionBoard: true, stickers: true, tools: true },
    components: {
      es: "Agenda A5, calendario, vision board, set completo de stickers y herramientas de enfoque adicionales.",
      en: "A5 planner, calendar, vision board, full sticker set and extra focus tools.",
    },
  },
];

export const TEMPLATES: TemplatePreset[] = [
  {
    id: "floral-elegante",
    name: { es: "Floral elegante", en: "Elegant floral" },
    description: { es: "Flores delicadas, tonos rosa y anillado dorado.", en: "Delicate flowers, rose tones and gold binding." },
    accent: "#c98fa3",
    coverTypeId: "ilustrada-floral",
    bindingId: "anillado-dorado",
    coverSystemId: "romantica",
    ringColorId: "dorado",
    elasticColorId: "elastico-rosa",
    layoutMode: "horaria",
    tone: "poetica",
    visionStyleId: "floral",
    calendarStyleId: "ilustrado",
    stickerIds: ["creativo", "descanso", "dia-excelente", "recordatorio"],
  },
  {
    id: "abstracto-moderno",
    name: { es: "Abstracto moderno", en: "Modern abstract" },
    description: { es: "Formas geometricas y paleta azul-violeta.", en: "Geometric shapes and a blue-violet palette." },
    accent: "#5f74c8",
    coverTypeId: "ilustrada-abstracta",
    bindingId: "discos",
    coverSystemId: "intensa",
    ringColorId: "plateado",
    elasticColorId: "elastico-negro",
    layoutMode: "areas",
    tone: "intensa",
    visionStyleId: "abstracto",
    calendarStyleId: "bloques",
    stickerIds: ["creativo", "aprendizaje", "mini-meta", "importante"],
  },
  {
    id: "ejecutivo-cuero-negro",
    name: { es: "Ejecutivo cuero negro", en: "Executive black leather" },
    description: { es: "Cuero premium negro, empastado cosido y letras serias.", en: "Premium black leather, sewn binding, serious type." },
    accent: "#24211d",
    coverTypeId: "cuero-premium",
    bindingId: "cosido",
    coverSystemId: "ejecutiva",
    ringColorId: "negro",
    elasticColorId: "elastico-negro",
    layoutMode: "dual",
    tone: "filosofica",
    visionStyleId: "minimal-collage",
    calendarStyleId: "clasico",
    stickerIds: ["finanzas", "importante", "productivo"],
  },
  {
    id: "minimal-beige-grafito",
    name: { es: "Minimal beige/grafito", en: "Minimal beige/graphite" },
    description: { es: "Tapa minimalista, paleta neutra y tipografia limpia.", en: "Minimalist cover, neutral palette, clean type." },
    accent: "#766d63",
    coverTypeId: "minimalista",
    bindingId: "anillado-negro",
    coverSystemId: "minimalista",
    ringColorId: "negro",
    elasticColorId: "elastico-crema",
    layoutMode: "libre",
    tone: "serena",
    visionStyleId: "minimal-collage",
    calendarStyleId: "minimal-numeros",
    stickerIds: ["descanso", "recordatorio", "productivo"],
  },
  {
    id: "creativo-colorido",
    name: { es: "Creativo colorido", en: "Colorful creative" },
    description: { es: "Lino texturizado con colores vivos y sellos jugetones.", en: "Textured linen with vivid colors and playful stamps." },
    accent: "#db7b36",
    coverTypeId: "lino",
    bindingId: "anillado-dorado",
    coverSystemId: "creativa",
    ringColorId: "dorado",
    elasticColorId: "elastico-rosa",
    layoutMode: "areas",
    tone: "intensa",
    visionStyleId: "moodboard",
    calendarStyleId: "bloques",
    stickerIds: ["creativo", "dia-excelente", "mini-meta", "aprendizaje"],
  },
  {
    id: "premium-rose-gold",
    name: { es: "Premium rose gold", en: "Premium rose gold" },
    description: { es: "Cuero vegano rosado con acabados rose gold.", en: "Blush vegan leather with rose gold finishes." },
    accent: "#c98f80",
    coverTypeId: "cuero-vegano",
    bindingId: "cuero-flexible",
    coverSystemId: "editorial",
    ringColorId: "rose-gold",
    elasticColorId: "elastico-rosa",
    layoutMode: "horaria",
    tone: "poetica",
    visionStyleId: "moodboard",
    calendarStyleId: "ilustrado",
    stickerIds: ["dia-excelente", "descanso", "recordatorio", "salud"],
  },
  {
    id: "neutro-profesional",
    name: { es: "Neutro profesional", en: "Neutral professional" },
    description: { es: "Gris grafito y estructura clara para cualquier perfil.", en: "Graphite gray with clear structure for any profile." },
    accent: "#4d5a63",
    coverTypeId: "tapa-dura",
    bindingId: "anillado-negro",
    coverSystemId: "minimalista",
    ringColorId: "negro",
    elasticColorId: "elastico-negro",
    layoutMode: "dual",
    tone: "filosofica",
    visionStyleId: "minimal-collage",
    calendarStyleId: "clasico",
    stickerIds: ["productivo", "importante", "finanzas"],
  },
  {
    id: "mistico-celestial",
    name: { es: "Mistico celestial", en: "Celestial mystic" },
    description: { es: "Sol dorado sobre rosa, para dias intuitivos y ambiciosos.", en: "Golden sun on blush, for intuitive and ambitious days." },
    accent: "#d9707a",
    coverTypeId: "ilustrada-mistica",
    bindingId: "anillado-dorado",
    coverSystemId: "romantica",
    ringColorId: "dorado",
    elasticColorId: "elastico-rosa",
    layoutMode: "libre",
    tone: "poetica",
    visionStyleId: "moodboard",
    calendarStyleId: "ilustrado",
    stickerIds: ["dia-excelente", "recordatorio", "mini-meta"],
  },
  {
    id: "retro-divertido",
    name: { es: "Retro divertido", en: "Fun retro" },
    description: { es: "Colores pastel en degrade, stickers y mucha energia.", en: "Gradient pastel colors, stickers and lots of energy." },
    accent: "#8fd6c9",
    coverTypeId: "ilustrada-retro",
    bindingId: "discos",
    coverSystemId: "creativa",
    ringColorId: "rose-gold",
    elasticColorId: "elastico-rosa",
    layoutMode: "areas",
    tone: "intensa",
    visionStyleId: "moodboard",
    calendarStyleId: "bloques",
    stickerIds: ["creativo", "dia-excelente", "descanso", "mini-meta"],
  },
  {
    id: "poetico-reflexivo",
    name: { es: "Poetico / reflexivo", en: "Poetic / reflective" },
    description: { es: "Tonos tierra, frases profundas y paginas libres.", en: "Earth tones, deep quotes and free-form pages." },
    accent: "#8b6f47",
    coverTypeId: "lino",
    bindingId: "cosido",
    coverSystemId: "editorial",
    ringColorId: "cobre",
    elasticColorId: "elastico-crema",
    layoutMode: "libre",
    tone: "poetica",
    visionStyleId: "floral",
    calendarStyleId: "minimal-numeros",
    stickerIds: ["descanso", "recordatorio", "salud"],
  },
];
